# Generated by Django 6.0.5 on 2026-05-06 09:39

import backend.models
import django.core.validators
import django.db.models.deletion
import django_mysql.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandFiberLookup',
            fields=[
                ('lookup_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=200)),
                ('clothing_type', models.CharField(max_length=200)),
                ('fiber_json', models.TextField()),
                ('dominant_fiber', models.CharField(default=None, max_length=200, null=True)),
                ('biodeg_score', models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True)),
                ('biodeg_tier', django_mysql.models.EnumField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'brand_fiber_lookup',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', django_mysql.models.EnumField(choices=[('PENDING', 'Pending'), ('CLAIMED', 'Claimed'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('ARCHIVED', 'Archived')], default='PENDING')),
                ('is_flagged', models.BooleanField(default=False)),
                ('delivery_method', django_mysql.models.EnumField(choices=[('PICKUP', 'Pickup'), ('DELIVERY', 'Delivery')], default=None, null=True)),
                ('flag_reason', models.TextField(default=None, null=True)),
                ('auto_archive_at', models.DateTimeField(default=None, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('rejection_reason', models.CharField(default=None, max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_barangay', models.CharField(max_length=50)),
                ('pickup_city', models.CharField(max_length=50)),
                ('pickup_display_address', models.TextField()),
                ('pickup_latitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('pickup_longitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('preferred_pickup_date', models.DateTimeField()),
                ('preferred_pickup_window_start', models.TimeField()),
                ('preferred_pickup_window_end', models.TimeField()),
            ],
            options={
                'db_table': 'donations',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', django_mysql.models.EnumField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')])),
                ('subscription_tier', django_mysql.models.EnumField(choices=[('FREE', 'Free'), ('PRO', 'Pro')])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('upload_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'uploads',
            },
        ),
        migrations.CreateModel(
            name='DonationItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('condition_rating', django_mysql.models.EnumField(choices=[('NEW', 'New'), ('LIKE_NEW', 'Like New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')])),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=8)),
                ('is_archived', models.BooleanField(default=False)),
                ('donation', models.ForeignKey(db_column='donation_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backend.donation')),
                ('lookup', models.ForeignKey(db_column='lookup_id', on_delete=django.db.models.deletion.RESTRICT, related_name='donation_items', to='backend.brandfiberlookup')),
            ],
            options={
                'db_table': 'donation_items',
            },
        ),
        migrations.CreateModel(
            name='InventoryLedger',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('usage_amount_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('weight_before_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('current_weight_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('lifecycle_status', django_mysql.models.EnumField(choices=[('ACTIVE', 'Active'), ('PENDING_ARCHIVE', 'Pending Archive'), ('ARCHIVED', 'Archived')], default='ACTIVE')),
                ('exit_state', django_mysql.models.EnumField(choices=[('UPCYCLED', 'Upcycled'), ('SHREDDED', 'Shredded'), ('LANDFILL', 'Landfill')], default=None, null=True)),
                ('is_upcyclable', models.BooleanField(default=True)),
                ('low_stock_threshold', models.DecimalField(decimal_places=3, default=Decimal('1.3'), max_digits=10)),
                ('was_forced_archived', models.BooleanField(default=False)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(default=None, null=True)),
                ('notes', models.TextField(default=None, null=True)),
                ('source_donation', models.ForeignKey(db_column='source_donation_id', on_delete=django.db.models.deletion.RESTRICT, related_name='inventory_ledger_entries', to='backend.donation')),
            ],
            options={
                'db_table': 'inventory_ledger',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('lalamove_order_id', models.CharField(default=None, max_length=50, null=True)),
                ('status', django_mysql.models.EnumField(choices=[('ASSIGNING_DRIVER', 'Assigning Driver'), ('ON_GOING', 'On Going'), ('PICKED_UP', 'Picked Up'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')])),
                ('dropoff_display_address', models.TextField()),
                ('dropoff_latitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('dropoff_longitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('has_been_edited', models.BooleanField(default=False)),
                ('scheduled_at', models.DateTimeField(default=None, null=True)),
                ('expires_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('no_reassigned', backend.models.TinyIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(255)])),
                ('donation', models.ForeignKey(db_column='donation_id', on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='backend.donation')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('order_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', django_mysql.models.EnumField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')])),
                ('payment_reference', models.CharField(default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='backend.order')),
            ],
            options={
                'db_table': 'order_payments',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', django_mysql.models.EnumField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')])),
                ('payment_reference', models.CharField(default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(db_column='subscription_id', on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='backend.subscription')),
            ],
            options={
                'db_table': 'subscription_payments',
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='upload',
            field=models.ForeignKey(db_column='upload_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_proofs', to='backend.upload'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=70)),
                ('role', django_mysql.models.EnumField(choices=[('Donor', 'Donor'), ('TUAB', 'TUAB'), ('Admin', 'Admin')])),
                ('first_name', models.CharField(default=None, max_length=50, null=True)),
                ('last_name', models.CharField(default=None, max_length=50, null=True)),
                ('middle_name', models.CharField(default=None, max_length=50, null=True)),
                ('business_name', models.CharField(default=None, max_length=125, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('social_link', models.TextField(default=None, null=True)),
                ('max_active_claims', backend.models.TinyIntegerField(default=3, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('target_fibers', models.TextField(default=None, null=True)),
                ('min_biodeg_score', models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True)),
                ('max_distance_km', models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True)),
                ('operational_status', django_mysql.models.EnumField(choices=[('ACTIVE', 'Active'), ('HIBERNATING', 'Hibernating'), ('ARCHIVED', 'Archived')], default=None, null=True)),
                ('contact_no', models.CharField(max_length=13)),
                ('barangay', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('display_address', models.TextField(blank=True, null=True)),
                ('maya_customer_id', models.CharField(default=None, max_length=50, null=True)),
                ('maya_card_id', models.CharField(default=None, max_length=20, null=True)),
                ('status', django_mysql.models.EnumField(choices=[('ACTIVE', 'Active'), ('UNDER_REVIEW', 'Under Review'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='UNDER_REVIEW')),
                ('is_2fa_enabled', models.BooleanField(default=False)),
                ('totp_secret', models.CharField(default=None, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documentation', models.ForeignKey(db_column='documentation_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentation_users', to='backend.upload')),
                ('upload', models.ForeignKey(db_column='upload_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_photo_users', to='backend.upload')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.RESTRICT, related_name='subscriptions', to='backend.user'),
        ),
        migrations.CreateModel(
            name='MatchPrediction',
            fields=[
                ('pair_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_match', models.BooleanField()),
                ('pct_target_fiber', models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True)),
                ('biodeg_target_fiber', models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True)),
                ('match_prob', models.DecimalField(decimal_places=5, max_digits=6)),
                ('distance_km', models.DecimalField(decimal_places=3, default=None, max_digits=8, null=True)),
                ('is_archived_version', models.BooleanField(default=False)),
                ('recommendation_status', django_mysql.models.EnumField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING')),
                ('tuab_rejection_reason', models.TextField(default=None, null=True)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.RESTRICT, related_name='match_predictions', to='backend.donationitem')),
                ('tuab', models.ForeignKey(db_column='tuab_id', on_delete=django.db.models.deletion.RESTRICT, related_name='match_predictions', to='backend.user')),
            ],
            options={
                'db_table': 'match_predictions',
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='claimed_by_tuab',
            field=models.ForeignKey(db_column='claimed_by_tuab', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_claimed', to='backend.user'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(db_column='donor_id', on_delete=django.db.models.deletion.RESTRICT, related_name='donations_as_donor', to='backend.user'),
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=100)),
                ('fields_modified', models.CharField(default=None, max_length=100, null=True)),
                ('ip_address', models.CharField(default=None, max_length=45, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(db_column='actor_id', on_delete=django.db.models.deletion.RESTRICT, related_name='audit_events', to='backend.user')),
            ],
            options={
                'db_table': 'audit_trail',
            },
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('api_token_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=None, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='backend.user')),
            ],
            options={
                'db_table': 'api_tokens',
            },
        ),
    ]
