# Generated by Django 6.0.5 on 2026-05-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(db_column='password_hash', max_length=70),
        ),
    ]
