# Generated by Django 6.0.5 on 2026-05-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_user_max_distance_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandfiberlookup',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
