# Generated by Django 6.0.5 on 2026-05-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_brandfiberlookup_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandfiberlookup',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
