# Generated by Django 6.0.5 on 2026-05-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_brandfiberlookup_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
