# Generated by Django 6.0.5 on 2026-05-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_user_maya_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='audittrail',
            name='notes',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rejection_reason',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
