# Generated by Django 6.0.5 on 2026-05-12 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_audittrail_notes_user_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audittrail',
            name='notes',
        ),
    ]
