# Generated by Django 6.0.5 on 2026-05-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_remove_audittrail_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='maya_customer_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
