# Generated by Django 6.0.5 on 2026-06-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_drop_framework_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchprediction',
            name='match_prob',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
    ]
