# Generated by Django 6.0.5 on 2026-06-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_match_prob_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchprediction',
            name='match_prob',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
    ]
