# Generated by Django 6.0.5 on 2026-06-20 18:47

import django_mysql.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_revert_match_prob_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=django_mysql.models.EnumField(choices=[('EMAIL_UNVERIFIED', 'Email Unverified'), ('UNDER_REVIEW', 'Under Review'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='UNDER_REVIEW'),
        ),
    ]
