# Generated by Django 6.0.5 on 2026-06-21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0021_alter_user_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="brandfiberlookup",
            old_name="category",
            new_name="product_name",
        ),
    ]
